name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main   # or rahul

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: List repo contents
        run: ls -R


      - name: Install dependencies
        run: npm install
        working-directory: sympo/frontend


      - name: Build React app
        run: npm run build
        working-directory: sympo/frontend


      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEKHORA_26 }}
          projectId: tekhora-26
          channelId: live
          entryPoint: sympo/frontend
